### ISSUE TITLE
Scala Templates not being processed by Grunt

### ISSUE THREAD

**Issue by milliondreams** [tuplejump/play-yeoman#35]
@kompot @jtammen 

This is following the comment -
https://github.com/tuplejump/play-yeoman/issues/12#issuecomment-32167677

> Don't know whether I did something wrong or it's not there - when running ~run everything works ok, but after dist I see the same template, without being processed by Grunt.
> 
> I mean blocks like
> 
> 
> <link rel="stylesheet" href="/ui/styles/sus.css">
> 
> are the same in production templates after dist task.
> 
> Am I missing anything?
> 
> Seems like there is hard coded app dir in this code
> https://github.com/tuplejump/play-yeoman/blob/develop/sbt-yeoman/app/com/tuplejump/sbt/yeoman/Yeoman.scala#L102-L108
> that should be changed to dist when running in production?

I am assuming that you have index.scala.html and it is getting compiled as a play view but not being processed by Grunt? Is my assumption correct?

Can you share a sample app for me to try out and debug the issue?

**Comment by Shiti** [comment]
From, 0.9.0, templates are generated on compile.
