### ISSUE TITLE
Play run works fine, but using start script generated by "stage" task returns empty screen

### ISSUE THREAD

**Issue by jschaul** [tuplejump/play-yeoman#36]
Hi,

thanks for this plugin, with "play run", the workflows of play and grunt integrate nicely. 
```
play run
```
followed by pointing a browser to localhost:9000/ui/ works as expected.

However, taking as an example the yo-demo app (I also tried with a freshly scaffolded "yo angular" app under folder /ui"), doing the following gives problems:

```
play clean compile stage
./target/universal/stage/bin/yo-demo
``` 
gives this output:
```
Play server process ID is 78065
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
```
But on `localhost:9000/ui/` I get a blank screen. 
On firefox or Chrome I get a blank screen together with 404 not found:
```
GET http://127.0.0.1:9000/ui/ [HTTP/1.1 404 Not Found 4ms]
```
Note that normal scala template views show under their respective url, so `localhost:9000/oldhome` for example with yo-demo works fine. 

Am I doing something wrong or is this a bug?

Thanks!

Additional information:
```
play 2.2.1 built with Scala 2.10.2 (running Java 1.7.0_10)
sbt.version=0.13.0
#in plugins.sbt:
addSbtPlugin("com.tuplejump" % "sbt-yeoman" % "0.6.3")
```

**Comment by Shiti** [comment]
related to #40
