### ISSUE TITLE
dependence on successful grunt build

### ISSUE THREAD

**Issue by jschaul** [tuplejump/play-yeoman#40]
Hello,

currently the `play stage` or `dist` task executes the grunt process, waits for it, but irrespectively whether that process succeeded or failed continues on to package the application. 
Is there a way to at least optionally configure this plugin to fail and stop when grunt fails? If grunt fails that's an indication that something in the code is wrong or tests failed, and that means the overall build should fail - especially in the context of continuous integration and deployment - I don't want to deploy a broken new version when there are problems in the build. 

Thanks for your work, is has proved very valuable so far.

**Comment by PR-O** [comment]
Any news on this issue @milliondreams ? Now play-yeoman supports running Grunt without the --force flag by setting Yeoman.forceGrunt := false, Play still continues building and deploying, irrespective of the failed Grunt build.

It would be great to have an optional flag to stop the Play build in case of an aborted Grunt build.

**Comment by Shiti** [comment]
Updated `stage` and `dist` tasks to throw an error when `grunt` fails if `Yeoman.forceGrunt:= false` but the build is not stopped.
