### ISSUE TITLE
Publish Scala 2.11 version

### ISSUE THREAD

**Issue by diwa** [tuplejump/play-yeoman#49]
Can you publish play-yeoman for scala 2.11 ? Our new play 2.3 applications are based on scala 2.11.1

Thanks.

**Comment by nlhkh** [comment]
`grunt serve` still serves the files correctly, but when I run with play, none of the bower_components and fonts where loaded.

**Comment by Shiti** [comment]
@nlhkh check the property `yeoman.devDirs`. The default is ["ui/app","ui/.tmp"]. If bower_components is not present in one of these, you will need to update the setting in your project's build file.

**Comment by Shiti** [comment]
Closing this issue as a version for Scala 2.11 has been published.
