### ISSUE TITLE
Please add a developer guide

### ISSUE THREAD

**Issue by yarinb** [tuplejump/play-yeoman#66]
Hi,

I'd like to add some patches to this as it's a great plugin for my current project. The problem is I'm not a SBT expert and can't find a way to build this project from scratch and run my play app against a dev build. For the time being, I just used the plugin sources as a part of my play app.

Could you please provide a developer guide for this plugin? How does one build it (SBT plugin & the play app part)? How do I push it to my local ivy repo? (similar to "mvn install")

Having this will be great!

**Comment by Shiti** [comment]
@yarinb What are the additional features you would like to see in the plugin? 

Working on this plugin requires knowledge of SBT. To use the plugin locally, you need to publish the projects `play-yeoman` and `sbt-yeoman` locally using the SBT command - `publishLocal`

**Comment by yarinb** [comment]
@Shiti This is actually a very good developer guide :) `publishLocal` is what I was looking for. Thanks.
