### ISSUE TITLE
Cannot resolve build.sbt

### ISSUE THREAD

**Issue by chrisqiu** [tuplejump/play-yeoman#67]
Unable to resolve build.sbt

error: object Project is not a member of package play
play.Project.playJavaSettings ++ Yeoman.yeomanSettings
        ^

Here is the full content of build.sbt:

//import play.Project._
import com.tuplejump.sbt.yeoman.Yeoman

name := """chris-application"""

version := "1.0-SNAPSHOT"

//playDefaultPort := 8080

resolvers += "Sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"

libraryDependencies ++= Seq(
  javaJdbc,
  javaEbean,
  cache,
  "org.webjars" %% "webjars-play" % "2.3.0-3",
  "org.webjars" % "bootstrap" % "3.3.2-1",
  "com.typesafe.slick" %% "slick" % "2.1.0",
  //  "org.slf4j" % "slf4j-nop" % "1.7.7",
  "mysql" % "mysql-connector-java" % "5.1.31",
  "com.h2database" % "h2" % "1.4.180",
  "com.github.nscala-time" %% "nscala-time" % "1.2.0"
)

play.Project.playJavaSettings ++ Yeoman.yeomanSettings

playScalaSettings

Yeoman.withTemplates

net.virtualvoid.sbt.graph.Plugin.graphSettings

fork in run := true

scalaVersion := "2.11.5"

build.properties:
sbt.version=0.13.5

plugins.sbt:
// Comment to get more information during initialization
logLevel := Level.Warn

// The Typesafe repository
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.8")

addSbtPlugin("com.tuplejump" % "sbt-yeoman" % "0.7.1")

addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.7.4")

I am guessing this concerns resolving dependencies but have no idea what goes wrong exactly.
Any help would be appreciated.

**Comment by Shiti** [comment]
can you un-comment `import play.Project._` and try?

**Comment by chrisqiu** [comment]
Thank you for reply. I've already tried it and here is what I got.

play-app/build.sbt:1: error: object Project is not a member of package play
import play.Project._
            ^
[error] Type error in expression

**Comment by Shiti** [comment]
@chrisqiu Please check without adding play-yeoman dependency. If its working without that, I will look into it further.

**Comment by chrisqiu** [comment]
I just resolved the problem by downgrading.

I am guessing I cannot use Scala 2.11 with it, as there seems no sbt-plugin for Scala 2.11.
http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/sbt-plugin/
