### ISSUE TITLE
Unable to use `Gruntfile.coffee` as the gruntfile?

### ISSUE THREAD

**Issue by hanfeisun** [tuplejump/play-yeoman#69]
When `Gruntfile.coffee` is used instead of `Gruntfile.js` as the gruntfile, `play-yeoman` will throw an ERROR:

Reading "Gruntfile.js" Gruntfile...ERROR
Fatal error: Unable to find "/Users/hanfeisun/Documents/waycanon/ui/Gruntfile.js" Gruntfile.

I think `Grunt` support to use coffeescript as the gruntfille natively, is it possible for `play-yeoman` to support this..

**Comment by Shiti** [comment]
This is configurable using the setting `yeomanGruntfile`
