### ISSUE TITLE
Run `npm install && bower install` within `activator run`

### ISSUE THREAD

**Issue by hanfeisun** [tuplejump/play-yeoman#71]
For easier deployment to Heroku, would it be possible to run `npm install && bower install` automatically when `activator run` `activator compile` or `sbt dist` is executed?

Current when I push my source code with play-yeoman to heroku, it will just throw an error: 

`Fatal error: Unable to find local grunt.`

**Comment by Shiti** [comment]
Installing grunt is a [pre-requisite](https://github.com/tuplejump/play-yeoman#prerequisites) to use the plugin

**Comment by hanfeisun** [comment]
I agree `grunt-cli` and `bower` are pre-requisites, and I've already installed them globally, but a local `grunt` still needs to be installed by `npm install`..

**Comment by hanfeisun** [comment]
I reopened this issue. Sometimes I added a new package in `package.json`or `bower.json`, but for easier deployment, I think it would be
