### ISSUE TITLE
Use `Content-Encoding:gzip` to serve static files?

### ISSUE THREAD

**Issue by hanfeisun** [tuplejump/play-yeoman#73]
Is it possible for play-yeoman to serve static files using `Content-Encoding:gzip`?

**Comment by Shiti** [comment]
Playframework Assets has Gzip support ([documentation](https://www.playframework.com/documentation/2.3.x/Assets)). Are you referring it to something else?

**Comment by hanfeisun** [comment]
Souldn't `play-yeoman` use Gzip to serve static files by default?

And would there be any document about how to use gzip encoding to serve resources within play-yeoman?

**Comment by hanfeisun** [comment]
Thanks! This could be closed..
