### ISSUE TITLE
Instructions lack indication of which repository has the sbt-plugin

### ISSUE THREAD

**Issue by mackler** [tuplejump/play-yeoman#76]
I am wanting to try using this plugin, and am following the directions in the [README](https://github.com/tuplejump/play-yeoman/blob/develop/README.md).  I have copied the `addSbtPlugin` line into my `project/plugins.sbt` exactly, changing only the version number as the README instructs.  I am using Play version 2.4.0 and Scala 2.11, so I used sbt-yeoman version 0.8.0 as the README says.  My line looks like:

    addSbtPlugin("com.tuplejump" % "sbt-yeoman" % "0.8.0")

When I start `sbt` the plugin is not found:

    [warn] 	module not found: com.tuplejump#sbt-yeoman;0.8.0
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	::          UNRESOLVED DEPENDENCIES         ::
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	:: com.tuplejump#sbt-yeoman;0.8.0: not found
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 
    [warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
    [warn] 		com.tuplejump:sbt-yeoman:0.8.0 (scalaVersion=2.10, sbtVersion=0.13)

I also tried changing the `%` to a `%%` between the organization and artifact name, but that failed also.

I see the output says `(scalaVersion=2.10`.  I'm not sure, but I think that refers to the version `sbt` is using, not my application.  I have this line:

    scalaVersion := "2.11.6",

in my `build.sbt` and my `project/build.properties` contains

    sbt.version=0.13.8

So I'm guessing that I must add a `resolvers` setting to my `project/lugins.sbt`, but I am ignorant what it should be.  The README says nothing about where the plugin is distributed from.

If this indeed is the problem, then it would be helpful if the README included instructions for properly setting the necessary `resolvers` so `sbt` can locate this plugin.  Thank you.

**Comment by Shiti** [comment]
v0.8.0 has now been published to Maven. It will be available in some time

**Comment by mackler** [comment]
It works now.  Thank you very much for the prompt response!
