### ISSUE TITLE
Start the build for the yo-injection-demo does not work

### ISSUE THREAD

**Issue by pylesage** [tuplejump/play-yeoman#89]
Hi,

If you try to build the yo-injection-demo:
> sbt dist

Then unzip the yo-injection-demo\target\universal\yo-injection-demo-1.0.0.zip
Then simply run the app in the bin folder 

The project starts but the angular app do not show up correctly.
Some missing ressources in the console are shown and the minimified script blows up with following error : Uncaught ReferenceError: angular is not defined.
Any idea how to make the demo ready to deploy ? 

May be this could be related in some way to the issue #86 ??

Regards,
Pierre-Yves

**Comment by Shiti** [comment]
These are the commands I ran,

```shell
$ sbt dist
$ unzip target/universal/yo-injection-demo-1.0.0.zip
$ cd yo-injection-demo-1.0.0/
$ bin/yo-injection-demo 
```

I was able to access all the paths defined in the routes file. Closing this issue as I was unable to replicate it.
