### ISSUE TITLE
Support for Play 2.5.x

### ISSUE THREAD

**Issue by rahulkumar-aws** [tuplejump/play-yeoman#91]
Hi,
Is any current plan for supporting Play 2.5.x version.

**Comment by carlosFattor** [comment]
+

**Comment by renexdev** [comment]
I've just tried to add the play-yeoman module to a new Play 2.5 app (addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.0")), after following all the steps suggested for play 2.4.x I got the following error when run in sbt...

ProvisionException: Unable to provision, see the following errors: 1) Error injecting constructor, java.lang.AbstractMethodError: com.tuplejump.playYeoman.Yeoman.play$api$mvc$Results$_setter_$TooManyRequests_$eq(Lplay/api/mvc/Results$Status;)V at com.tuplejump.playYeoman.Yeoman.<init>(Yeoman.scala:47) while locating com.tuplejump.playYeoman.Yeoman for parameter 1 at router.Routes.<init>(Routes.scala:43) while locating router.Routes while locating play.api.inject.RoutesProvider while locating play.api.routing.Router for parameter 0 at play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:200) while locating play.api.http.JavaCompatibleHttpRequestHandler while locating play.api.http.HttpRequestHandler for parameter 4 at play.api.DefaultApplication.<init>(Application.scala:220) at play.api.DefaultApplication.class(Application.scala:220) while locating play.api.DefaultApplication while locating play.api.Application

Any idea on how to solve it? It is a matter or Play versionning? 
Thanks in advance
ReneX

**Comment by Shiti** [comment]
@renexdev The issue you are facing is because the plugin only has support till 2.4.x. We are working on supporting 2.5.x

**Comment by renexdev** [comment]
Great!! You are a genius guys! Cheers!

**Comment by carlosFattor** [comment]
Are you foreseeing to support a new version of Angular 2.0 ?

**Comment by Shiti** [comment]
published 0.9.0 for Play 2.5.x.

@carlosFattor Although We used Angular example for the demo, you can use any yeoman generator and it should work with the plugin since the plugin has no dependencies on Angular.

**Comment by rahulkumar-aws** [comment]
@Shiti  Thanks a lot :-)

**Comment by renexdev** [comment]
Thanks a lot!
