### ISSUE TITLE
Unresolved Yeoman.yeomanSettings  in the 0.9.0

### ISSUE THREAD

**Issue by nuwan1025** [tuplejump/play-yeoman#93]
Hi,
I am upgrading play-java app to play 2.5. My build.sbt file cant find the yeomanSettings when configured as in documentation for 0.9.0 tuplejump.

  val appSettings = Seq(version := appVersion, libraryDependencies ++= appDependencies) ++
  Yeoman.**yeomanSettings** 

But I got it working by changing  it to
 Yeoman.**projectSettings** 

Is this a documentation mistake?

**Comment by Shiti** [comment]
Starting from 0.9.0, the plugin is an auto-plugin and its configuration is documented in the `README`. Please make sure you enable the plugin. Refer the [demo](https://github.com/tuplejump/play-yeoman/tree/develop/yo-demo) to make sure you got it right. If it doesn't work even after that, please share your build file or a sample project for us to look into.

**Comment by nuwan1025** [comment]
Thanks for the reply.My build.sbt was like this.

lazy val root = (project in file(".")).enablePlugins(PlayJava, Yeoman, PlayEbean).settings(
  Yeoman. yeomanSettings: _*
}

I removed the settings part and it is working.I think for the 0.9.0 auto plugin version, we do not need to call 
.settings(
  Yeoman. yeomanSettings: _*
}
(I got confused with the following line in documentation
Note: If you're using build.sbt instead of the full scala build, you need to place the 2 additions above into build.sbt as follows:)

Please correct me if I am wrong...
Thanks

**Comment by Shiti** [comment]
@nuwan1025 After the note, you need to check the sample code for the corresponding version

**Comment by nuwan1025** [comment]
When I run the application as an play app in my ide it worked fine. But when I try to package it with activator dist command, it doesnt package the ui part. Hence the grunt file is not read.
(Configured build.sbt as in the documentation)

I found the solution for that and it is working fine for me.
lazy val root = (project in file(".")).enablePlugins(PlayJava, Yeoman, PlayEbean).settings(
  com.tuplejump.sbt.yeoman.Yeoman.projectSettings: _*
)

**Comment by malterb** [comment]
@shiti I was running into the same issue as @nuwan1025 and was able to fix it with his workaround

**Comment by enragedginger** [comment]
I too faced the same issue as @nuwan1025 and was able to fix it with his workaround. This should be documented as I feel it's relevant to #86, #90, and #95

**Comment by jmcardon** [comment]
@nuwan1025 Thank you for this workaround!
